Fix AttributeError: 'EarlyPython' object has no attribute 'hide' (#22)
* Fix AttributeError: EarlyPython has no attribute hide

Use util.attr() for safe attribute access in EarlyPython.get_code()
instead of directly accessing self.hide which may not exist in older
serialized rpyc files. Add regression test.